language: node_js
node_js:
- 10.16.2
install: npm install
cache:
  directories:
  - node_modules
script: npm test
branches:
  only:
  - master
  - dev
before_install:
- openssl aes-256-cbc -K $encrypted_95bbcdc7725b_key -iv $encrypted_95bbcdc7725b_iv
  -in deploy_rsa.enc -out deploy_rsa -d
addons:
  ssh_known_hosts: 18.162.125.153
before_deploy:
  - openssl aes-256-cbc -K $encrypted_95bbcdc7725b_key -iv $encrypted_95bbcdc7725b_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 /tmp/deploy_rsa
  - ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/ ubuntu@18.162.125.153:~/ER-backend
          && ssh ubuntu@18.162.125.153 'cd ER-backend && pm2 start ecosystem.config.js'
  on:
    branch: master
